server:
  port: 7071

spring:

  application:
    name: spring-jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: db.properties
  jpa:
    show-sql: true
    # generate-ddl: true
    defer-datasource-initialization: never
    hibernate:
      ddl-auto: none
      format-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect
  sql:
    init:
      # mode: always
      platform: mysql

